# Site settings
title: Patrick's blog
email: d.conghoang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "patrickdinh.github.io" # the base hostname & protocol for your site
github_username:  patrickdinh

#URL settings
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
highlighter: pygments